name: gitleaks

on: [push]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@v1.6.0
